"""Add breach monitoring fields

Revision ID: efac78d33bf5
Revises: 32efa2514e8b
Create Date: 2026-04-30 10:56:48.919152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efac78d33bf5'
down_revision: Union[str, Sequence[str], None] = '32efa2514e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault', sa.Column('breach_count', sa.Integer(), nullable=True))
    op.add_column('vault', sa.Column('last_checked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault', 'last_checked')
    op.drop_column('vault', 'breach_count')
    # ### end Alembic commands ###
